[project]
name = ""
version = ""
description = ""
authors = [
    {name = "sibir007", email = "sibiriakoff2006@yandex.ru"},
]
dependencies = []
requires-python = ">=3.8"
readme = "README.md"
license = {text = "MIT"}

